### ISSUE TITLE
Role moderation

### ISSUE THREAD

**Issue by super-cooper** [super-cooper/memebot#5]
**Is your feature request related to a problem? Please describe.**
Nick is a vicious tyrant and has made himself the only admin of the server.

**Describe the solution you'd like**
A simple command to allow users to moderate themselves _and only themselves_ in roles. Users should be allowed to use the command to create a role, add themselves to roles, and remove themselves from roles. The only roles that will be excluded from this feature are `@Kings` and `@Queens`. The commands should probably be like `!role create <name>`, `!role join <name>`, and `!role leave <name>`.

**Describe alternatives you've considered**
Possibly adding an alias for video games like `!playing <name>` which will auto create the group and add you to it. Not sure what a good alias for leaving the game would be though. Maybe it would also be better to make an alias `!group` since that is sort of the way we are using roles in this context. We could also add an alias `!home` and `!nothome`.

**Additional context**
This will be useful for creating easily taggable aliases for games that not all of us play. We currently have `@rocketleague`, but it would be nice if everybody could set these up and configure them themselves at will.

**Comment by nhawke** [comment]
possible option argument of time to alow for automatic removal from a role after a given time. particularly useful for putting yourself in self-imposed timeout

`!role join <name> [time]` where `time` would be in format of `X{w,d,h,m}` to timeout after `X` weeks, days, hours, or minutes, etc

**Comment by super-cooper** [comment]
My understanding of timeout was like being temporarily banned from the server so you can focus, but I do like the concept of having the role "time out" with the optional argument. If you also wanted the disciplinary "timeout," it should probably be a separate issue because that would need to be a reserved role with different permissions than normal. The user would also need to be removed from `@Kings` or `@Queens` during that time, no?

**Comment by nhawke** [comment]
> My understanding of timeout was like being temporarily banned from the server so you can focus, 

Yes and it is usually self imposed (but for now i have to mediate it because users can't impose it on themselves. 

>that would need to be a reserved role with different permissions than normal. The user would also need to be removed from `@Kings` or `@Queens` during that time, no?

yeah. the role already exitsts. It is only cosmetic though because simple removing the kings or queens role will effectively lock you out of everthing. Any actual "Timeout" role would be cosmetic really.

Because this involves toggling a role, maybe it should be bundled here. A good way to do timeouts actually would just be to leave Kings or Queens for a set time, but a time argument would be required when leaving Kings or Queens because otherwise you permanently lock yourself out.

**Comment by super-cooper** [comment]
>yeah. the role already exitsts. It is only cosmetic though because simply removing the kings or queens role will effectively lock you out of everything. Any actual "Timeout" role would be cosmetic really.

>Because this involves toggling a role, maybe it should be bundled here. A good way to do timeouts actually would just be to leave Kings or Queens for a set time, but a time argument would be required when leaving Kings or Queens because otherwise you permanently lock yourself out.

Yeah, we could just make a `!timeout` alias to do all of this, and it would have a required time param or default to an hour or something. It would check if the caller is in `@Kings` or `@Queens` and remove them, and then store that information somewhere. We would probably have to spawn another thread that just sleeps for the timeout period, and then adds the user back. We would also need to persist this thread somehow in case MemeBot goes down during the timeout period, so we don't have to add the user back manually. Because of the scope of this, I think having timed addition and removal from roles should be a separate issue.

**Comment by goopydudest** [comment]
> Because of the scope of this, I think having timed addition and removal from roles should be a separate issue.

I agree with this. I think addressing timed addition and removal of roles deals with a lot of back-end issues that don't really have to do with "role moderation" which is a very user-facing scope.

**Comment by goopydudest** [comment]
I started designing a solution for this today but I've run into an issue that I'm having trouble thinking through. Roles in a guild are given an int ID as their primary key, as such role lookup is based around these int ID's and Guilds are also able to support roles with duplicate names. Due to this, we are going to have to figure out how to do role lookup by name (str) within a Guild. Also, we have to think of how we can have users specify which role they want to edit or enforce some sort of no duplicate role name abstraction.

**Comment by goopydudest** [comment]
>we are going to have to figure out how to do role lookup by name (str) within a Guild

I just looked and saw that there's a builtin that returns every role inside of a Guild so this is no longer an issue.
